### ISSUE TITLE
wrong image size when flashing 

### ISSUE THREAD

**Issue by MYEUHD** [n4ru/1vyrain#101]
I'm trying to install skulls on an X230 using 1vyrain
I give the rom image using a web server, it is received but it doesn't get flashed.
 I get
``Error: Image size (8388608 B) doesn't match the flash chip's size (12582912 B)!``
``All done! Press enter key to restart your thinkpad (etc.)``

when I reboot, I have the same stock BIOS as before

**Comment by digmorepaka** [comment]
Nothing is flashed because no valid link to a rom was entered

**Comment by MYEUHD** [comment]
You are correct
I was providing an http link but it was redirecting to https. That's why it wasn't working.
Thanks!
