### ISSUE TITLE
Host image on Github

### ISSUE THREAD

**Issue by axelsimon** [n4ru/1vyrain#102]
Is there a reason to not host the image directly on Github, using the release feature?
They'd be nicely hosted at https://github.com/n4ru/1vyrain/releases

Also, if this were to be automated, with a bit more work and with this [Github action](https://github.com/sigstore/cosign-installer), you would be able to relatively easily sign releases using Sigstore's cosign, and get much better than a md5 hash (which is deprecated, but i'm sure you know that).

Thanks for the project in any case!

**Comment by digmorepaka** [comment]
> Is there a reason to not host the image directly on Github, using the release feature?

Not really but also not really much reason *to* use it either at the moment. 

The MD5 is intended as an integrity check of the download and was chosen because it appears to be the easiest to verify across different platforms.
