### ISSUE TITLE
Remove soft power adapter lock?

### ISSUE THREAD

**Issue by rzfzr** [n4ru/1vyrain#104]
I believe that the w530 was sold with both 170w and 135w adapters, depending on cpu config (dual vs quad core).
So when I plug a smaller adapter into my w530, and I get this:
```
 The connected AC adapter has a lower wattage than the recommended
 model which was shipped with the system. To boot with the AC adapter,
 please connect the AC adapter which was shipped with the system.
 Press Esc to continue. 
```
It must be a software lock, such is the wifi whitelist, any ideas on how to remove it?
I'm aware of the jumper solution: https://forums.lenovo.com/t5/ThinkPad-P-and-W-Series-Mobile-Workstations/W530-Power-Adapters-90W-vs-135W-Vs-170W/m-p/841161?page=7#1227911

**Comment by digmorepaka** [comment]
EC throttle, UEFI lockout. On most models it seems to let you go through if you press F1

**Comment by rzfzr** [comment]
Will try it out soon, Thanks

**Comment by biblicabeebli** [comment]
iirc the power brick will work when the device is off (charge the battery), but if it is on it draws no power.

(I thought the 135w/170w worked on a w530, it was the ~90w and lower models didn't. I have a w530, I tried to cut down on bag weight with a lesser charger but couldn't because of this.)
