### ISSUE TITLE
x230 " vmlinuz not found ..bootable with rufus

### ISSUE THREAD

**Issue by surya334** [n4ru/1vyrain#106]
when it starts booting .. what appears is the words " vmlinuz : not found " I have set the bios to the uefi position and I have disabled secure bios.

**Comment by digmorepaka** [comment]
Did you use DD or ISO mode in rufus

**Comment by surya334** [comment]
1. I use the dd rule ..MBR -- Uefi...the result is when I boot I select the usb drive then press enter and then it goes back to boot options like that.
2. I use GPT rules --- Uefi with iso settings (not dd mode)... I try to boot and select the usb drive .. he wants to enter but it says " vmlinuz not found".
3. i use the cd drive to boot.. i burn it using nero burning. managed to enter the ivyrain image and detect the device. but when SP3 (sleep mode)...press the power button it won't wake up..I've tried many times but it still doesn't wake up.

**Comment by digmorepaka** [comment]
This image is not meant for an optical device. Try writing it with win32diskimager.

**Comment by surya334** [comment]
I have also tried using "win32diskimager". but still like number 1.. can't boot

my os "windows 10 extreme lite

**Comment by digmorepaka** [comment]
Re-download the image, and use a different usb drive

**Comment by surya334** [comment]
unfortunately i only have one usb drive...and now my laptop won't boot. just a beep with the power light indicator on.. after it turns off..and lights up...then turns off....just like that.
