### ISSUE TITLE
Non-Volatile Variable Storage is About Full on W530

### ISSUE THREAD

**Issue by grandinquirer** [n4ru/1vyrain#109]
Computer: Thinkpad W530
OS: Qubes OS (UEFI)

I flashed stock 1vyrain a couple days ago and was successfully able to use it for a few days, but 2 days ago, Qubes OS crashed and my computer rebooted to an error that said "Non-Volatile Variable Storage is About Full." I had ME cleaner disabled, but other than that, my BIOS was pretty much stock. When I opened /sys/firmware/efi/efivars, there were a bunch of dump files taking up space, so I deleted them and booted without issue. After about an hour of use, the same error occured (and after this crash I was forced to reinstall Qubes). Today the same error occured, but there were no dump files in efivars. I tried re-enabling Intel ME and was able to successfully boot, but I got the same error and crash 15 minutes later. I just reset my BIOS and added a new EFI entry, and it is working fine so far, but I am afraid it will happen again. I read that Intel ME is necessary for UEFI and that a UEFI operating system would only be able to run for about 30 minutes until a crash, but mine worked fine for a few days. If the issue really is that I had ME disabled, is there any way around this such as running ME cleaner on the 8MB chip? I have not heard about this issue for people running Tianocore and ME cleaner, but so that is a possible workaround I considered as I want the security that comes with a disabled/reduced ME.`

**Comment by digmorepaka** [comment]
Probably a qubes/configuration issue. cbf to read the text wall. Load defaults and try with a different OS.

**Comment by n4ru** [comment]
digmo woke up and chose violence today, but I concur. It's probably unrelated as this is the first I'm hearing of something like this. Feel free to reopen if you can nail it down more explicitly to an 1vyrain issue, though I find that highly improbable.

**Comment by grandinquirer** [comment]
> digmo woke up and chose violence today, but I concur. It's probably unrelated as this is the first I'm hearing of something like this. Feel free to reopen if you can nail it down more explicitly to an 1vyrain issue, though I find that highly improbable.

Thank you, I will do so. So just to be clear, Intel ME doesn't have to be enabled to boot an OS in UEFI mode?

**Comment by n4ru** [comment]
You do not need it enabled for UEFI mode, the 30 minute shutdown is if you completely remove it IIRC.
