### ISSUE TITLE
1vyrain -> Coreboot/Skulls

### ISSUE THREAD

**Issue by hhartzer** [n4ru/1vyrain#113]
Hi!

I've been very happily running my x230 with 1vyrain for a while now. Wanted to give Coreboot/Skulls a try, though. I re-wran 1vyrain, and when it comes back up it says the BIOS is still write-protected, which is confusing because it worked initially.

Is there something I should do or run so I can get 1vyrain to run again, and pass it the Skulls image? Or is there a better avenue?

Thank you!

**Comment by digmorepaka** [comment]
it's literally telling you what's wrong

**Comment by hhartzer** [comment]
Sorry, I'm not sure what I'm missing. After the x230 comes back up from suspend, it says: "BIOS still write-protected! Something went wrong or your device is not compatible. Exiting."

I don't see any more instructions or details from there.
