### ISSUE TITLE
Boot error, help needed

### ISSUE THREAD

**Issue by firefoxlover** [n4ru/1vyrain#114]
I did IVprep as I used 1vyrain before and want to use Coreboot now.

I flashed the newest release 1vyrain.iso using Balena etcher, ventoy and dd, used this command:

`sudo dd bs=4M if=/path/to/iso of=/dev/sdc status=progress && sync`

In Bios i set "prioritize UEFI", disabled secureboot and rollback prevention, enabled user to flash Bios.

Flashing successful, but booting gives always the same result:

```
BOOT FAILED!
This live system image failed to boot.
Please file a bug against the 'live-boot' package or email the live system mailing list at <debian-live@lists.debian.org>, making sure to note the exact...

The file /boot.log contains some debugging information...

Live-boot will now start a shell. The error message was:

Unable to find a medium containing the live file system

Busybox v.1.30.1 ...

(initframfs)
```

**Comment by digmorepaka** [comment]
Balena etcher and ventoy are unreliable garbage. If you wrote it with dd/win32diskimager and it doesn't work your usb drive or source image are bad. Before booting load UEFI defaults and set boot to UEFI Only.

**Comment by firefoxlover** [comment]
@digmorepaka In my experience Ventoy and BalenaEtcher create bootable drives very reliably, where dd just fails. I will try again and report findings.
