### ISSUE TITLE
Is it possible to add the available NvmeexpressDxe module?

### ISSUE THREAD

**Issue by JerryCheng1** [n4ru/1vyrain#128]
I would like to know if there is a possibility to add an available nvmeexpressDxe module to this ivybridge-based xx30 thinkpads UEFI Bios with an optional nvme startup? I tried to find a lot of nvme ffs but they are all based on the AMI BIOS and even after adding the module via UEFITool, it doesn't boot properly after flashing the modified BIOS via SOP clip.

**Comment by digmorepaka** [comment]
Sadly the answer is likely no, during the development of ThinkMods NVMe adapter there were a few attempts but it wouldn't cooperate. 
Easiest method we found is loading NvmExpressDxe via opencore.
