### ISSUE TITLE
CRC error doesn't go away?

### ISSUE THREAD

**Issue by Niiisse** [n4ru/1vyrain#129]
Hi, I've flashed the 1vyrain bios to a previously corebooted Thinkpad w530 (I've bought it with Coreboot and wanted to get rid of it.) Everything seems to have gone well, but when I boot, I get the Thinkpad splash screen and the CRC error. However, whatever I do I can't get rid of the CRC error. I can't open setup either, this just gives me a blank screen with a single underscore.

Any advice would be much appreciated!

**Comment by digmorepaka** [comment]
CMOS settings are corrupted(or rather completely different incompatible format between coreboot and Lenovo UEFI) in a way which doesn't let you enter UEFI SETUP. Try reflashing coreboot, changing cmos options to something different than what they are and reflash factory UEFI
