### ISSUE TITLE
question, change vid pid on the whitelist

### ISSUE THREAD

**Issue by iddq** [n4ru/1vyrain#13]
Is it possible to change a vid pid on the whitelist instead of patching the BIOS?

Thank you.

**Comment by n4ru** [comment]
Probably, but out of scope for 1vyrain.

**Comment by iddq** [comment]
Where is the vid pid list located?

**Comment by n4ru** [comment]
It's located in the EFI module "LenovoWMAPolicy" of the BIOS.
