### ISSUE TITLE
Backlit keyboard no longer working.

### ISSUE THREAD

**Issue by dcam2016** [n4ru/1vyrain#131]
I had 1vyrain on my T430 and it was running great other than an Intel Platform device in the device manager showing as not working due to not enough resources for the device. I downgraded the BIOS using IVPrep, then put 1vyrain back on it. That sorted out the issue in the device manager but now my backlit keyboard no longer works. Fn+Space activates the thinklight but not the keyboard lights. I could be totally tripping but I was sure there was an option in the bios about the keyboard light which isn't there now. Ideas?

**Comment by digmorepaka** [comment]
That's weird, 1vyrain has nothing to do with EC functions like keyboard backlight or thinklight. The backlight should breathe on breathe off on power up, if it doesn't you may have a dead backlight. If it does it may be configured in vantage or something to be thinklight only.

**Comment by dcam2016** [comment]
Yeah no breathing, it's dead lol. It acts like there is no backlight there, i.e. Fn+Space toggles the thinklight only, no going through the keyboard lights. It must have been chance that it happened at the same time as redoing 1vyrain. Thinkvantage doesn't show any backlight keyboard. I'll have a look in Ubuntu live, see if it can see it. Thanks for the reply.
