### ISSUE TITLE
X230 black screen after ivyrain x330 bios update

### ISSUE THREAD

**Issue by theeason123** [n4ru/1vyrain#132]
Went through the process fine. After the installation was completed the laptop booted with a blank screen. According to Reddit, the x330 bois defaults to an external monitor. In order to resolve this a docking station and external monitor is required. Thought I’d report it here.

**Comment by digmorepaka** [comment]
That rom disables LVDS. If you flashed it on a machine without the FHD/QHD kit, that is expected behavior.
