### ISSUE TITLE
Update supported BIOS to latest 2.82 version as it seems that Lenovo will not be updating it anymore.

### ISSUE THREAD

**Issue by HolimaX** [n4ru/1vyrain#133]
Lenovo is not anymore supporting T430, thus this update would serve as last grand improvement to this legendary laptop and platform!

**Comment by HolimaX** [comment]
See https://github.com/n4ru/1vyrain/issues/134 for additional feature.

**Comment by digmorepaka** [comment]
Already is 2.82(G1ETC2WW)
![2024-08-29_19-47](https://github.com/user-attachments/assets/eb8302af-3f4b-4ff2-943e-dcf2f21e139f)
