### ISSUE TITLE
error 0271 clock error

### ISSUE THREAD

**Issue by alexanderpowerplays** [n4ru/1vyrain#141]
so i did the ivyrain "jailbreak" successfully but i didnt remove the bios password because i didnt know how to and so i ended up with a supervisor password that i couldnt make it through and so i removed all power and the cmos battery in hopes of something that didnt happen but i did end up bypassing that password and getting into the bios and now i have a problem that is unfixable, the problem is that i cant boot up the laptop without the 0271 clock error showing up, when i try to press ESC in order to boot anyways it reboots and then im brought to that same exact screen and so i press esc again and it reboots and brings me back to that screen over and over and because of the bios patch i get the advanced menu at the cost of the clock menu

if anyone can help me bypass this error, fix the error, or release a patch for ivyrain that doesnt remove the clock tab in the bios

one thing id recommend is that you tell people how to remove the passwords from the bios as to help other people like me

**Comment by alexanderpowerplays** [comment]
update: it just booted past the RTC error

**Comment by alexanderpowerplays** [comment]
if you need to remove the supervisor password all you need to do is set a new password by inputting the current password and leaving 'new password' and 'confirm new password' blank

**Comment by digmorepaka** [comment]
> if anyone can help me bypass this error, fix the error, or release a patch for ivyrain that doesnt remove the clock tab in the bios

You need to put the advanced tab *somewhere*, clock can be set form OS. As is mentioned in the FAQ. If you don't want the advanced tab, build a rom without advanced menu.
![RTFM](https://i.imgur.com/VwS5Fnb.png)

> one thing id recommend is that you tell people how to remove the passwords from the bios as to help other people like me

We do.
![RTFM](https://i.imgur.com/6oGSBWl.png)

> if you need to remove the supervisor password all you need to do is set a new password by inputting the current password and leaving 'new password' and 'confirm new password' blank 

You got lucky here, most of the time you need to short the eeprom and do the bypass
https://www.youtube.com/watch?v=5z0HdLqgR_I

**Comment by alexanderpowerplays** [comment]
> > You got lucky here, most of the time you need to short the eeprom and do the bypass if the password is not cleared rather only disabled and unkown https://www.youtube.com/watch?v=5z0HdLqgR_I

> i did have to short the eeprom to bypass the password because it got corrupted

**Comment by alexanderpowerplays** [comment]
![68747470733a2f2f692e696d6775722e636f6d2f366f475342576c2e706e67](https://github.com/user-attachments/assets/b46336fe-299a-4605-8b87-d2668f1781f6)

it says to clear it but not how

it needs to tell you HOW to clear it not tell you TO clear it

theres a difference between telling people to clear it and telling them how to clear it

**Comment by alexanderpowerplays** [comment]
You need to put the advanced tab somewhere, clock can be set form OS. As is mentioned in the FAQ. If you don't want the advanced tab, build a rom without advanced menu. 
![68747470733a2f2f692e696d6775722e636f6d2f56775335466e622e706e67](https://github.com/user-attachments/assets/99c67ae5-d746-4cd2-a8de-d0ed135b3995)

i couldnt even get into the OS as it wouldnt ignore the error and continue until i powered the laptop on 6 whole hours later so having the clock option as a submenu in the advanced stuff could be a good fix

**Comment by alexanderpowerplays** [comment]
you also made so many spelling errors im surprised you didn't notice the rec squiggly lines

**Comment by digmorepaka** [comment]
> it says to clear it but not how
> 
> it needs to tell you HOW to clear it not tell you TO clear it
> 
> theres a difference between telling people to clear it and telling them how to clear it

The first result on google is a lenovo support page spoonfeeding you directly how to do it.
If that's too challenging for you, don't mess with your laptop's firmware.

> i couldnt even get into the OS as it wouldnt ignore the error and continue until i powered the laptop on 6 whole hours later so having the clock option as a submenu in the advanced stuff could be a good fix

within 3 restarts it will let you into the OS, Due to the way phoenix is, we can't add(or remove) a tab at the top - only replace it, and we can't move the tab menu to a list menu because of the same issue, memory speed limiter menu is a good example of this, the 3 auto options are there because we couldn't remove 800 and 1066 that were bricking machines, only replace them.

> you also made so many spelling errors im surprised you didn't notice the red squiggly lines

You don't get to be butthurt at a project published by volunteers for free. You don't get to nitpick spelling mistakes on documentation of a free project written by non native english speakers while you yourself can't be bothered to add any commas so your sentences are easier to read. You're nitpicking the tiniest shit possible that caused you problems because **you didn't read the instructions**, you expect your hand to be held the entire time while that person feeds you with a silver spoon. This is not kindergarten, we're not your caretakers, it's time to grow up and teach at least one or two braincells to think before you do. Instead of acting like a child you should realize that you should appreciate the fact that you get any of this for free and with any kind of documentation.

If you don't like the project, don't use it, and don't be a dick about it.

**Comment by alexanderpowerplays** [comment]
> You don't get to be butthurt at a project published by volunteers for free. You don't get to nitpick spelling mistakes on documentation of a free project written by non native english speakers while you yourself can't be bothered to add any commas so your sentences are easier to read. You're nitpicking the tiniest shit possible that caused you problems because **you didn't read the instructions**, you expect your hand to be held the entire time while that person feeds you with a silver spoon. This is not kindergarten, we're not your caretakers, it's time to grow up and teach at least one or two braincells to think before you do. Instead of acting like a child you should realize that you should appreciate the fact that you get any of this for free and with any kind of documentation.

i wasn't nitpicking spelling mistakes on the documentation, rather on you're response. (i do apologize if what i said came off as rude)

just so you know, i did read the documentation and was suggesting that you added useful information to help other people who want to do this bios mod as well since there's probably a good amount people out there who could end up in a similar situation that i ended up in.

all i really asked for was for you to add some very useful information to help prevent people from ending up with what is essentially a 'bricked laptop'.

**Comment by alexanderpowerplays** [comment]
> > i couldnt even get into the OS as it wouldnt ignore the error and continue until i powered the laptop on 6 whole hours later so having the clock option as a submenu in the advanced stuff could be a good fix
> 
> within 3 restarts it will let you into the OS, Due to the way phoenix is, we can't add(or remove) a tab at the top - only replace it, and we can't move the tab menu to a list menu because of the same issue, memory speed limiter menu is a good example of this, the 3 auto options are there because we couldn't remove 800 and 1066 that were bricking machines, only replace them.

this is good to know, thank you for telling me.

**Comment by alexanderpowerplays** [comment]
> If that's too challenging for you, don't mess with your laptop's firmware.

it isnt too challenging for me

**Comment by alexanderpowerplays** [comment]
> > it says to clear it but not how
> > it needs to tell you HOW to clear it not tell you TO clear it
> > theres a difference between telling people to clear it and telling them how to clear it
> 
> The first result on google is a lenovo support page spoonfeeding you directly how to do it. If that's too challenging for you, don't mess with your laptop's firmware.
> 
> > i couldnt even get into the OS as it wouldnt ignore the error and continue until i powered the laptop on 6 whole hours later so having the clock option as a submenu in the advanced stuff could be a good fix
> 
> within 3 restarts it will let you into the OS, Due to the way phoenix is, we can't add(or remove) a tab at the top - only replace it, and we can't move the tab menu to a list menu because of the same issue, memory speed limiter menu is a good example of this, the 3 auto options are there because we couldn't remove 800 and 1066 that were bricking machines, only replace them.
> 
> > you also made so many spelling errors im surprised you didn't notice the red squiggly lines
> 
> You don't get to be butthurt at a project published by volunteers for free. You don't get to nitpick spelling mistakes on documentation of a free project written by non native english speakers while you yourself can't be bothered to add any commas so your sentences are easier to read. You're nitpicking the tiniest shit possible that caused you problems because **you didn't read the instructions**, you expect your hand to be held the entire time while that person feeds you with a silver spoon. This is not kindergarten, we're not your caretakers, it's time to grow up and teach at least one or two braincells to think before you do. Instead of acting like a child you should realize that you should appreciate the fact that you get any of this for free and with any kind of documentation.
> 
> If you don't like the project, don't use it, and don't be a dick about it.

throughout this whole entire back and forth i haven't been much of a dick, yet you have the audacity to call me a dick after being a dick through the majority of this comment.

i thought this community was better than that, i hope you have a good day and grow to be a better person as being a collaborator in this project i would expect for you to be the bigger man in this discussion since the last paragraph is just you being a complete dick to me which i did not appreciate. I will try and grow to be a better person in the future as you should be doing too since people will not want to interact with a community after being sent a response like yours.
