### ISSUE TITLE
X230 - Several SQUASHFS errors leading to failed patch

### ISSUE THREAD

**Issue by beesyrupfactory** [n4ru/1vyrain#143]
Hello, I'm having a bit of a unique issue, and I wanted to see if I could get some help resolving this.

1. Around 2 years ago, I purchased an X230, ran hamishcoleman's ec patches in hopes of getting the X220 keyboard and battery whitelisted.
2. I also ran 1vyprep, and 1vyrain and everything went fine.
3. I upgraded the BIOS to the latest 2.77 without any issues. All of the 1vyrain advanced settings were present, and I was able to drive my non-Lenovo whitelisted wifi/bt card.
4. I had my X230 shelved for a while, and I realized that I didn't perform a crucial step in the EC patch where I actually installed the keyboard whitelist. During that time, since 1vyrain was operational, I think I may have disabled Intel ME which I suspect to be the root cause of this behavior, but I'm not really knowledgeable about BIOS operations so I can't say for sure.
6. I downgraded my firmware to BIOS 2.75 (G2ETB5WW) EC 1.14 (G2HT35WW), and ran the thinkpad EC patches for x230.
7. I then ran IVprep, and downgraded to 2.60
8. Afterwards, I prepped the latest version of 1vyrain ISO using DD on a 2GB drive, disabled secure boot, enabled UEFI only.
9. I got into the boot menu, then selected my prepped USB drive, went through the process, but noticed there was a warning:
```
Can't autodetect IBM/Lenovo ThinkPad X230, DMI info unavailable.
At least some flash regions are read protected. You have to use a flash
layout and include only accessible regions. For write operations, you'll
additionally need the --noverify-all switch. See manpage for more details.
```
As seen in the following screenshot, it looks like it's ready to go:
![IMG_6339](https://github.com/user-attachments/assets/68b0731d-7c73-4c1c-b11f-e5d7715d3f66)

10. After pressing Enter, it goes through the S3 sleep, and I power it back on.
11. After I get to the point where it says `Please enter a choice` I select `1` for Flash Modified Lenovo BIOS.
12. Shortly after I press Enter again, I get the following output (sorry, I've been having a hard time outputting text, so here's a screenshot):
![IMG_6340](https://github.com/user-attachments/assets/96cf8c6e-8195-4815-aec2-5d439d014d96)

13. I dropped to shell and run `poweroff`
14. I installed my Wifi card and restarted
15. The following output is printed and halts the system:
![IMG_6341](https://github.com/user-attachments/assets/6fd609de-0d28-4286-8436-ac0a7e9d8d6e)

If I remove my card, and reboot, I have no problems booting in.

Am I missing something, or have I borked my system?

Any tips/insight would be sincerely appreciated.

Thank you!

**Comment by digmorepaka** [comment]
Try a different usb drive/different USB port

**Comment by beesyrupfactory** [comment]
Absolutely brilliant @digmorepaka !

Thanks so much. That was exactly it. Tried another flashing with another USB stick, and it successfully flashed the latest 1vyrain. Whitelist is working perfectly. This was another case of PEBCAK. Closing this request.
