### ISSUE TITLE
x131e Support

### ISSUE THREAD

**Issue by jwhitehorn** [n4ru/1vyrain#17]
It'd be awesome to see support for Ivy Bridge equipped x131e Thinkpads.

**Comment by n4ru** [comment]
Theoretically possible since it's the same series (I think?), but I am definitely not comfortable adding support without having one of these machines to test on.

**Comment by jwhitehorn** [comment]
I'd love to help, but I do not have a spare machine I could send you. Do you think this is something I could assist with? Not even sure where/how to start, but more than happy to jump in.

**Comment by n4ru** [comment]
Hop in our discord and we can chat about it.

https://discord.gg/Ybdz7AS

**Comment by n4ru** [comment]
After doing some searching, it looks like the actual BIOS patches might be incompatible so we'd need to make new ones, but if it's the Intel Ivybridge model it might still be doable.

The Intel patch notes do have a BIOS update at the same time as the other xx30 series that patches the same bugs, so it is definitely vulnerable (at least the Intel models are).

**Comment by n4ru** [comment]
The new [long form FAQ](https://medium.com/@n4ru/1vyrain-an-xx30-thinkpad-jailbreak-fd4bb0bdb654) has instructions for testing compatibility on currently unsupported machines.
