### ISSUE TITLE
Lack of Date/Time Config

### ISSUE THREAD

**Issue by hh1209** [n4ru/1vyrain#19]
Got this flashed on my T430 with no issues. However, the laptop's battery died (of course the CMOS battery is garbage), so the BIOS bothered me to set the clock. I went into the BIOS to change it, and I could not find the Date/Time config that usually resides in one of the top tabs.

Maybe I'm crazy, but I couldn't find the setting. Thanks for your work on these laptops, keeping them alive! The thinkpad community really appreciates it.

**Comment by n4ru** [comment]
Huh. You're not blind, the Advanced Menu tab replaces the tab.

If you boot into an OS it should update the time in the BIOS as well. Not sure if there's a good fix for this.

Were you the one that emailed me about this issue as well? Just saw it earlier today.

**Comment by hh1209** [comment]
Thanks for getting back to me. Yes, that was me emailing you. It worried me
for a second because it refused to boot twice because of date and time, but
it worked after that, and I guess Linux set the hardware clock.

So I guess it's not really a big deal, especially if it's not an easy fix.

Thanks again for your contributions,
-Henry
