### ISSUE TITLE
Flashing whole 12Mb ROM, not just BIOS region

### ISSUE THREAD

**Issue by tlaurion** [n4ru/1vyrain#2]
Following https://github.com/gch1p/thinkpad-bios-software-flashing-guide

I understand that once running from a vulnerable bios, the s3 vulnerability can be used to unlock wp bits.

I'm on my way of providing shrinked ME and expended IFD for the x230 under Heads, once I figure out how to make coreboot module to depend on an external x230 blobs repository from board configuration, where the IFD and ME would be downloaded from, so Heads do not distribute them directly so that coreboot uses them when being built, freeing 5mb of additional usable space, deactivating and neutering it.

If I understand well, it would then be possible to actually flash the whole ROM, including the ME region and IFD, not just the BIOS region. Or did I miss something?

**Comment by tlaurion** [comment]
On a simpler level, can flashrom be used to read the whole flash?

**Comment by gch1p** [comment]
Short answer: no. You need to flash modified FD externally first.

**Comment by iddq** [comment]
Can you please tell me what is the 8M FL1 file and 12M FL2 file in the updates?

I'm talking about T530 and if I'm right it has one 8M and one 4M spi flash so that is 12M in total.

**Comment by firefoxlover** [comment]
interestingly, I have this new issue:

went this route:
1. stock bios
2. Ivyprep
3. 1vyrain, wanted to flash coreboot
4. ivyprep
5. tried 1vyrain instead again

now I cant flash 1vyrain again, as it says the image is only 8mb, but the available space is 12mb! This is actually great, but I dont get any network and confused what to do
