### ISSUE TITLE
Slower BIOS boot time after the mod.

### ISSUE THREAD

**Issue by MjehCastillo** [n4ru/1vyrain#20]
It now takes my X230 7-8 seconds for the Thinkpad boot logo to display immediately after pressing the power button before Windows 10 could start loading. Before the mod it took only 3 seconds. I have an SSD installed. Probably being nit picky here but I like my stuff to boot fast. My previous bios before the mod is 2.52. 
![image](https://user-images.githubusercontent.com/30916696/73129005-fad4e000-4014-11ea-8d83-59657728c05b.png)

**Comment by EdgarBaumgarten** [comment]
Can you check if the Quick Boot option in the BIOS enabled/disabled? Maybe that got toggled by the mod or perhaps by a reset prepping for the mod.

**Comment by n4ru** [comment]
Investigating

**Comment by MjehCastillo** [comment]
> 
> 
> Can you check if the Quick Boot option in the BIOS enabled/disabled? Maybe that got toggled by the mod or perhaps by a reset prepping for the mod.

Quick option is enabled, still the same.

**Comment by Nikuw** [comment]
Make sure you disabled legacy booting and CSM, as those can cause a longer boot time.

**Comment by n4ru** [comment]
Nothing about the mod inherently makes the BIOS boot slower from my testing, and I have not seen others experience this issue. Resetting your BIOS might cause some settings (such as those suggested above) to slow down your boot.

If you have any additional information to share, please feel free to update this thread.

**Comment by aericktoes** [comment]
I get this same behaviour on two different T430 motherboards. It takes about 5 more seconds for the BIOS bootsplash screen to appear. It's not a big deal for me, so I haven't done much testing myself.

**Comment by xXShalevElimelechXx** [comment]
Hi, sorry if this is considered a necrobump but I just want to make sure your intel ME is enabled, since disabling ME slows boot time,

**Comment by aericktoes** [comment]
Can confirm I get this behaviour when turning on and off ME. Thanks!

**Comment by MjehCastillo** [comment]
> 
> 
> I get this same behaviour on two different T430 motherboards. It takes about 5 more seconds for the BIOS bootsplash screen to appear. It's not a big deal for me, so I haven't done much testing myself.

Yeah this exactly fixed the issue, nice!

**Comment by n4ru** [comment]
Adding the ME quirk to the FAQ. Thanks.
