### ISSUE TITLE
X1 Carbon (gen 1) support? 

### ISSUE THREAD

**Issue by dkudriavtsev** [n4ru/1vyrain#22]
Will support for this board be added?

**Comment by n4ru** [comment]
I can investigate since it is the same year and is also IvyBridge. Hop in the [Thinkpad enthusiast discord](https://discord.gg/xVFx9vM) and we can chat. Start by downgrading your BIOS firmware as low as you can, and then I'll give you the next steps.

**Comment by n4ru** [comment]
The new [long form FAQ](https://medium.com/@n4ru/1vyrain-an-xx30-thinkpad-jailbreak-fd4bb0bdb654) has instructions for testing compatibility on currently unsupported machines.
