### ISSUE TITLE
Question about overclocking

### ISSUE THREAD

**Issue by rzfzr** [n4ru/1vyrain#23]
I have a 3740QM on a W530, what overclocking support is really given? Presets or full control? My goal would be to lower voltages...
Thanks

**Comment by digmorepaka** [comment]
You cannot decrease the voltage on ivy bridge. Only increase it. 3740QM has turbo bins and you can only increase the multiplier by a certain amount.

**Comment by n4ru** [comment]
You can increase voltage, and modify the clock multiplier by up to +4. There may be other minor tweaks related to overclocking (setting TDP), but these are the ones directly related to increasing your clock speed. This can be done either in XTU, ThrottleStop, or accessing the MSR directly.
