### ISSUE TITLE
Limiting number of cores does not work

### ISSUE THREAD

**Issue by thebiggestmac** [n4ru/1vyrain#29]
Setting Active core numbers is ignored and is always All after reboot.
Limiting CPUID does not have effect. Also, disabling AMT makes AMT active again after reboot.

My CPU: i7-3720QM. T430.

**Comment by n4ru** [comment]
The active core issue seems to be a bug in the Advanced Menu module, so cannot fix, but I will add this to the FAQ. Thank you.
