### ISSUE TITLE
Completed downgrade and then completed flashing with default image but cannot sign into the bios

### ISSUE THREAD

**Issue by rsramkis** [n4ru/1vyrain#3]
The problem I ran into is I cannot sign into my x230 bios at boot after I flashed it with the default image found here:

https://drive.google.com/file/d/1fh7Y-x-7X410Vo3Fyw0G1zZ-_pn21kVF
Pre-step:
-Bios had boot up password.

Steps:
(1) Ran the downgrade utility on my x230 from Window 10 x64 which downgraded the bios from 2.81 to 2.60.

(2) Verified after downgrade I could sign into the bios  and also boot into windows 10.

(3) I then booted from the USB drive into the default IVYRain image.

(4) The image successfully applied and then rebooted.

(5) I can get to the bios password sign in screen but it does not accept my password.

(6) I can see the text being typed.

**Comment by rsramkis** [comment]
I did reset the power on password by removing the cmos battery. But the supervisor password is not being accepted. These are the errors showing on the x230 screen after resetting the boot password.

![boot message after removing cmos battery](https://user-images.githubusercontent.com/14362317/72231413-4608e080-3589-11ea-9490-107966fd4cf8.jpg)

**Comment by n4ru** [comment]
I'll investigate this. It may be related to some settings not being cleared when BIOS is flashed with flashrom instead of the normal method. The downgrade is considered a "normal" flash so it would make sense that you had no issues there.

**Comment by rsramkis** [comment]
Pretty much used jumpers method to reset the system password with motherboard jumpers (not for the faint of heart. Different place then posted diagram. Cmos has 8 pins (pin 1 & 2 toward top of board) where cmos is sideways. Also remember to remove cmos battery.

After the system bios reset there was nothing else to do. I could see the advanced menu in the bios.

Recommend updating instructions:

Disable all passwords in bios.

Reset bios to default manually.

Downgrade must be performed (as my bios for x230 was still supporting flashing at 2.81.

On side note, what bios version should i be at after this flash? Just thinking of Intel vunerabilities.
