### ISSUE TITLE
Updating skulls: Reading old flash chip contents - transaction error between offset 0x00003000 and 0x0000303f

### ISSUE THREAD

**Issue by kahrkunne** [n4ru/1vyrain#30]
Refer to this issue, which I'm being told is on 1vyrain's end: https://github.com/merge/skulls/issues/142

**Comment by digmorepaka** [comment]
This is an issue of the iME region not being readable. This is not an 1vyrain issue, but user error. Run your flashrom command with the -N option. Flashrom tries to read the WHOLE chip before flashing and fails when it gets to the iME region.
