### ISSUE TITLE
Ability to undervolt with an i5?

### ISSUE THREAD

**Issue by SyedOmarNoor** [n4ru/1vyrain#33]
I'd like to have longer battery life because my x230 only runs for 2-3 hours, even with a good condition (52/57Wh) battery and all power saving measures taken.
Specs:
Intel Core i5 3380m
Windows 10 Pro
6-cell battery
240GB SSD

**Comment by n4ru** [comment]
Ivy Bridge does not have any undervolting features, but you can limit TDP.

**Comment by vitaly-zdanevich** [comment]
> but you can limit TDP

How? Please clarify. What numbers? Where?
