### ISSUE TITLE
Skulls image is 4.2 MB

### ISSUE THREAD

**Issue by ftondolo** [n4ru/1vyrain#34]
Hey, I want to use ivyrain to flash skulls to my x230, however, I have just noticed that the image is 4.2 MB and not 4 MB exactly.  How can I fix this?  Here's where I got it from: https://github.com/merge/skulls/releases/tag/0.1.8
Attached is the image.

[x230_coreboot_seabios_6af55e583d_top.rom.zip](https://github.com/n4ru/1vyrain/files/4335363/x230_coreboot_seabios_6af55e583d_top.rom.zip)

**Comment by n4ru** [comment]
The image you linked it exactly 4MB and the exact size of the vendor BIOS. Differentiating [MiB and MB](https://en.wikipedia.org/wiki/Mebibyte) is really annoying sometimes.

**Comment by rsramkis** [comment]
> Hey, I want to use ivyrain to flash skulls to my x230, however, I have just noticed that the image is 4.2 MB and not 4 MB exactly. How can I fix this? Here's where I got it from: https://github.com/merge/skulls/releases/tag/0.1.8
> Attached is the image.
> 
> [x230_coreboot_seabios_6af55e583d_top.rom.zip](https://github.com/n4ru/1vyrain/files/4335363/x230_coreboot_seabios_6af55e583d_top.rom.zip)

@ftondolo , Just curious. Did you successfully install coreboot from command line and not from a clip programmer after using the 1vyrain bios install?  Thanks (just looking to do this myself as 1vyrain bios successfully flashed a couple months ago.
