### ISSUE TITLE
X230T: virtualization disabled

### ISSUE THREAD

**Issue by shadowfoto** [n4ru/1vyrain#35]
not sure where the issue is, but since i've 1vyrained my X230T i cant use vt at all - its simply disabled and wont stay on if i toggle it in bios.
i think i could have a modbios from previous mobo where it worked, just in case, but not sure if its of any help

**Comment by digmorepaka** [comment]
VT-X or VT-D? Did you try clearing your settings completely? Which menu are you toggling it from?

**Comment by shadowfoto** [comment]
VTX, [Advanced -> Processor Configuration - Intel ® Virtualization Technology].
but i've just found that [Security] tree also has VT options that actually work if you toggle them, so guess its a false positive. could post cpuz if you still interested.

**Comment by digmorepaka** [comment]
No need.
