### ISSUE TITLE
Blind mode on X230 with WQHD screen

### ISSUE THREAD

**Issue by Houl777** [n4ru/1vyrain#39]
"Error no suitable video mode found. Booting in blind mode" on X230 with WQHD screen.
Test on official and test version.

P.s. Please add additional variant of BIOS (for X230/X330 with modded screen) with disabled native LVDS to see only 1 display in the OS

**Comment by digmorepaka** [comment]
Both of these issues have already been addressed, the blind mode issue fix is in the current testing image. The LVDS patched image is already available.

**Comment by Houl777** [comment]
Tried new version. Received next error.
Downgraded to 2.60 successfully.

![photo_2020-04-12_05-16-39](https://user-images.githubusercontent.com/29420363/79061185-aeb24700-7cb7-11ea-8308-f570e7433767.jpg)

**Comment by digmorepaka** [comment]
Updated.

**Comment by Houl777** [comment]
Good day.
Thanks. It works!
And i think will be excellent to add additional option for X330/X230 WQHD to re-flash BIOS with enabled LVDS if user will want to return brightness control. 
As i understood current option 1) will use internal display and user will receive Blank screen. Am i right?

**Comment by digmorepaka** [comment]
I don't understand your request, if you want LVDS enabled just choose option 1. If you want it disabled use option 0.

**Comment by Houl777** [comment]
Understood.
I meant that in unhacked BIOS version "Digital on dock" option was in use. Will i able to see not blank screen if someday i'll want to revert back brightness control?

**Comment by digmorepaka** [comment]
If you want to revert to LVDS enabled version of 1vyrain, you downgrade with IVprep and use 1vyrain live image again. In my testing the video signal appears on all connected displays so it shouldn't be an issues.

**Comment by Houl777** [comment]
Ok!
Thanks again!
