### ISSUE TITLE
X230 Tablet post-flash HDD2 issue

### ISSUE THREAD

**Issue by kfazz** [n4ru/1vyrain#4]
i flashed this on an X230t.
The EC was modded previously for kb swap.
started at 2.71, downgraded to 2.59 with gcuj19uc.iso
mod failed, flash unlock didn't work.
rolled back to 2.01 with gcuj08uc.iso.
flash worked, however i get an error every boot:
2101: Detection error on HDD2 (Mini SATA)

**Comment by n4ru** [comment]
Try using revision 1, which should have fixed issues with the x230t specifically.
