### ISSUE TITLE
Error when trying to flash skulls bios 

### ISSUE THREAD

**Issue by belkya** [n4ru/1vyrain#42]
When attempting to flash 4mb skulls bios on T430 I receive the error 
`error: image size (8388608B) doesnt match with the flash chips size (12582912B)`
Any help would be appreciated

**Comment by digmorepaka** [comment]
You gave an incorrect link or an empty image.

**Comment by belkya** [comment]
When inputting 
`wget https://github.com/belkya/coreboot/raw/master/x230_coreboot_seabios_6af55e583d_top.rom`
On my main system I receive no errors and the download completes normally.

I am using images from the skulls release page.

**Comment by digmorepaka** [comment]
You could have made a typo. Also why are you flashing a firmware compiled for X230 onto a T430?
