### ISSUE TITLE
Can this mod change the fan rpm of a X230?

### ISSUE THREAD

**Issue by Thomas12** [n4ru/1vyrain#43]
Hi,

can this BIOS mod change the fan-speed rpms of a Thinkpad X230 or does this happen in another part? The X230 fan speed on the lowest setting is too fast and therefore too loud. The X220 had a much lower minimum fan speed (at level 1) and was perfectly silent. I do not remember exactly, I think on the X220 it was 1000 or 1500 rpms for level 1 while the X230 started at 2000 rpms or so.

Thank you!

Thomas

**Comment by digmorepaka** [comment]
There might be the option to modify the EC curve in advanced menu but it is likely the same set thresholds for levels. The RPM ranges should be the same, try swapping the heatsink assembly with the fan from your X220 to your X230 and see if there is still a difference.
