### ISSUE TITLE
X230i jail break

### ISSUE THREAD

**Issue by ageryun** [n4ru/1vyrain#45]
I had below screen shot while I was in jail break of my thinkpad x230i.

![80682405-055fb380-8af5-11ea-9da0-69a373493a9f](https://user-images.githubusercontent.com/64578424/80696667-4a421500-8b0a-11ea-885b-15e819a26475.jpg)

bios was downgraded to 2.60 from 2.77. but still has same 'unsupported' message. Not sure if 'jail break' is done correctly. Can you please help me?

**Comment by digmorepaka** [comment]
X230i is identical to X230. Could you exit the script, run `dmidecode -t system` and post the output? To flash, after the 'compatible' screen run 
`dd if=/dev/zero of=/tmp/pad.bin bs=1M count=8` then
`cat /tmp/pad.bin /root/bios/X230.rom > /tmp/12M.rom` then
`/root/flashrom/flashrom -p internal:force_I_want_a_brick --ifd -i bios -N -w /tmp/12M.rom` then you can reboot.

**Comment by ageryun** [comment]
thanks for your comments. I did as per your advise but not sure if I did correctly.
![20200430_220823](https://user-images.githubusercontent.com/64578424/80720990-432dfd80-8b30-11ea-8712-f5c17b9c0aad.jpg)
![20200430_215626](https://user-images.githubusercontent.com/64578424/80721037-5214b000-8b30-11ea-8b2a-54cdd9ae0c0d.jpg)
![20200430_221155](https://user-images.githubusercontent.com/64578424/80721133-72dd0580-8b30-11ea-8c0a-6030a454298c.jpg)
It seems some regions are still locked. Of course, I changed bios settings to apply uefi tools before flashing.

**Comment by digmorepaka** [comment]
Sorry my bad, it is `/root/flashrom/flashrom -p internal:laptop=force_I_want_a_brick --ifd -i bios -N -w /tmp/12M.rom`. For the dmidecode command, it would be helpful if you scrolled up to the part where it says the machine model :sweat_smile:

**Comment by ageryun** [comment]
thanks. it looks the jailbreak is done. sorry. I didn't know how to scroll up the screen at  command mode. I ordered Intel 7260AC module for wifi and bluetooth 4.0.
![20200501_093746](https://user-images.githubusercontent.com/64578424/80801466-14bb2b80-8bdf-11ea-9eee-49bc3309657e.jpg)
Thank you!
