### ISSUE TITLE
Unable to boot from hard disk

### ISSUE THREAD

**Issue by budsbenzer** [n4ru/1vyrain#47]
After using 1vyrain on my T430s, I can no longer boot from the internal HDD. Either I get to the dialog where I can select the boot device, but selecting the HDD does nothing, or I end up with a blinking cursor on a black text mode screen. 

Booting from a USB flash drive still works. The HDD is recognized in the BIOS, as well as in the Lenovo diagnostics tool.

I tried both UEFI and legacy boot, as well as resetting the BIOS settings. No effect. Secure boot is disabled.

Does someone have a hint what to do?

Would flashing an official Lenovo BIOS help?

I'd be thankful for any help.

**Comment by digmorepaka** [comment]
What is likely happening is you have to re-generate your efivars. If you are using a linux distro boot with super grub disk and run update-grub. For windows to the same and run the equivalent of that for rebuilding the efi boot partition and efivars

**Comment by budsbenzer** [comment]
Thank you very much, reinstalling grub did it. The system boots from HD again!

Perhaps it would make sense to mention something along those lines in the FAQ?
