### ISSUE TITLE
Github wget Error

### ISSUE THREAD

**Issue by joshuayun61** [n4ru/1vyrain#48]
When I try to flash a custom rom from a github repo that I created with only that rom image, the following error appears.

ERROR: The certificate of www.github.com is not trusted
ERROR: The certificate of www.github.com doesn't have a known issuer.

This is preventing me from actually flashing the bios that I want to.

The github repo is here:
https://github.com/joshuayun61/thinkpad_t430_coreboot

I am running a T430 right now.

**Comment by joshuayun61** [comment]
I figured out that if there is the flag --no-check-certificate is in the wget, command, that would potentially resolve the issue, however, how would you recompile the iso after you change the script?

**Comment by Jan-E** [comment]
Try using a wget with Windows certificate store support. wget 1.19.4 for instance has no problem with downloading the rom:
https://eternallybored.org/misc/wget/

**Comment by joshuayun61** [comment]
I have no problem downloading it on my home machine, but I cannot download it on the flash during the 1vyrain execution script, I do not know how to use the windows binary in the flashing process.

**Comment by digmorepaka** [comment]
Try downloading this file from a http not https link.

**Comment by joshuayun61** [comment]
The same thing had happened when I used the http address, I am currently trying to Self-Build and trying to resolve errors in the chipsec in the start.sh script

**Comment by Jan-E** [comment]
That is because http://github.com/joshuayun61/thinkpad_t430_coreboot/blob/master/coreboot_seabios_top.rom redirects to the https address. You should put it somewhere on a server without redirect.

**Comment by joshuayun61** [comment]
I see, thanks for the input, do you know where such a site could be?

**Comment by digmorepaka** [comment]
[0x0 would be my recommendation](https://0x0.st)

**Comment by joshuayun61** [comment]
that did it thanks
