### ISSUE TITLE
Backups?

### ISSUE THREAD

**Issue by gch1p** [n4ru/1vyrain#5]
It seems, the script does not creates a dump of `bios` region before flashing (correct me if I'm wrong). I think it's a good idea to have backups, just in case.

Note that you can't dump whole 12M because of working ME, but you still can dump the `bios` region.

**Comment by n4ru** [comment]
Good call. I'll include this in the next version.

**Comment by digmorepaka** [comment]
Any particular reason for the backup to be necessary? As far as i can tell there are generic roms in the 1vyprep repo that a user can flash in case of a brick.

**Comment by gch1p** [comment]
Well, EFI variables are stored somewhere in ROM. I can imagine a situation where some OS was installed in UEFI mode and it's not possible (well, it's possible, just harder) to boot it with clean BIOS.

**Comment by n4ru** [comment]
Added.
