### ISSUE TITLE
Missing Date and Time settings for T430

### ISSUE THREAD

**Issue by josuesoto1** [n4ru/1vyrain#54]
Hi.. 
You made a great job on this mod for the bios. Everything is working fine. 
However I was not able to find the option to change the BIOS time and date. I am having some issues with my backup battery and the system keeps asking me to adjust the BIOS time and date. 
Can you give me the instructions to get the date and time changed within BIOS?

Thanks
Josue Soto

**Comment by digmorepaka** [comment]
https://github.com/n4ru/1vyrain#read-the-long-form-faq-before-opening-an-issue

https://medium.com/@n4ru/1vyrain-an-xx30-thinkpad-jailbreak-fd4bb0bdb654

Set it from OS.
