### ISSUE TITLE
/root/start.sh: line 70: setpci: command not found

### ISSUE THREAD

**Issue by unilock** [n4ru/1vyrain#56]
I run into this error on my X131e (i3-3227U, Ivy Bridge) after waking from S3 sleep. Attached is a photo of the log including the error.
![PXL_20201104_144200255](https://user-images.githubusercontent.com/11802133/98125112-0c8bc380-1e82-11eb-8530-1fc47d080746.jpg)

**Comment by Nable80** [comment]
``setpci`` tool is a part of ``pciutils`` package. It can be installed by running ``apt-get update && apt-get install pciutils`` or similar some command of your distro. Of course it should be run as root user before running ``start.sh``.

**Comment by digmorepaka** [comment]
Try downgrading your firmware until you find one that can be unlocked

**Comment by unilock** [comment]
@digmorepaka Even the oldest BIOS available (1.05, released 2012-05-31) doesn't work, so I believe something else is awry.

**Comment by unilock** [comment]
Attached is a log of `start.sh` from the live USB (acquired via `./start.sh >out.txt 2>&1`).
[out.txt](https://github.com/n4ru/1vyrain/files/5489089/out.txt)

**Comment by unilock** [comment]
Attached is an archive of logs taken while following https://github.com/gch1p/thinkpad-bios-software-flashing-guide.
[archive.zip](https://github.com/n4ru/1vyrain/files/5490887/archive.zip)
It seems that the FLOCKDN bit isn't being disabled after suspending after modifying the s3bootscript.
I have no idea what to do from here...

**Comment by Nable80** [comment]
You can implement this change (replace all occurrences instead of the first one) in ``modify_s3_reg`` function in ``chipsec/modules/tools/uefi/s3script_modify.py``.

Btw, using some external programmer is also an option, isn't it?

**Comment by unilock** [comment]
@Nable80 Attached is a modified version of s3script_modify.py that allows specifying width.
[s3script_modify.zip](https://github.com/n4ru/1vyrain/files/5502383/s3script_modify.zip)
It appears to work. I can modify both write-to-0xFED1F804 instructions to write 0x6009 instead of 0x0004E009 and 0xE008. However, after waking from sleep, FLOCKDN remains set to 1.
It's strange, because this device is definitely listed as vulnerable to the S3 boot script vulnerability ([LEN-2014-006](https://support.lenovo.com/at/en/product_security/s3_boot_protect))...

Using an external programmer is an option, but that sort of defeats the purpose of 1vyrain, no? Nonetheless, I have a CH341a on the way.

**Comment by Nable80** [comment]
I think you should replace 0xE008 with with 0x600**8**, not 0x6009. SMI# handler may set FLOCKDN too.

I'm also surprised by 0x0004E009 value because HSFS register is 16-bit wide. Probably it is interpreted as a write to both HSFS and HSFC regs and should be replaced with 0x00046009.

> Using an external programmer is an option, but that sort of defeats the purpose of 1vyrain, no?

I think it's not important if you're not doing some kind of so-called "evil main attack" and don't care about warranty. Flashing an improved firmware version is the main target after all.

**Comment by unilock** [comment]
Tried replacing 0xE008 with 0x6008 and 0x0004E009 with 0x00046009; still the same results. Is there any way to confirm that the SMI handler is setting FLOCKDN to 0xE008, or can we only assume?

My thought process was that 1vyrain is easier and cheaper (albeit by a few USD) than using an external programmer.
Though I guess the SPI flash is fairly easy to access on the X131e, so it doesn't matter all that much how you program it.

**Comment by Nable80** [comment]
Btw, you shouldn't modify opcode width, it can break the whole script. I've checked your logs and it actually has 4-byte first write and 2-byte second one.

> Is there any way to confirm that the SMI handler is setting FLOCKDN to 0xE008, or can we only assume?

SMI handler runs on its own, there's no way to control its behavior (except using your own firmware) and it's also hard to tell when it's triggered and what it actually does. So it's mostly a guess but there aren't many suspects here. I understand your pessimistic approach and I can even call it realistic. There are still more ideas to check (e.g. find some non-critical 4-byte write opcode and replace its address and data to overwrite one of flash protection registers) but I don't think they worth it.

**Comment by unilock** [comment]
I'm not modifying opcode width; my s3script_modify.py only allows specifying the target opcode width. It doesn't actually change it.

I haven't yet been able to test your suggestion, of changing 0xE008 to 0x6008 and 0x0004E009 with 0x00046009. I've been trying and failing to get chipsec to work on my X131e so I don't have to boot off the 1vyrain USB and replace s3script_modify.py every time, but the chipsec driver won't compile for some reason. I made an issue about it here: https://github.com/chipsec/chipsec/issues/1039

Also, another issue with 1vyrain that I've been struggling with: the live USB will only boot properly if it's the only bootable medium connected to the system. If I try selecting it from the boot menu (F12), the laptop just reboots, so I have to remove the HDD and let the machine boot off the USB without any user interaction.

**Comment by unilock** [comment]
Well, changing 0xE008 to 0x6008 and 0x0004E009 to 0x00046009 didn't work; FLOCKDN is still 1, and HSFS is still 0xE008. Guess something else is keeping FLOCKDN in check.

Disregarding my X131e-specific issues, it seems the 1vyrain live USB has a few problems itself:
1. It needs pciutils installed
2. It only boots when it's the only bootable volume attached to the system, for whatever reason

**Comment by digmorepaka** [comment]
pciutils missing will be rectified with a new release, ETA- when we get a few other laptops supported, not a high priority as the currently supported machines can be flashed without issue.

For it only booting when no other bootable volumes are attached, I'm not sure i quite understand what you mean by that. It's a UEFI image so there is no MBR, if your firmware is configured for MBR first it first checks for MBR on all drives then goes to EFI as far as I know. Could you specify your boot configuration and steps to replicate?

**Comment by unilock** [comment]
To reproduce:
1. Ensure BIOS is set to UEFI Only mode with CSM turned OFF
2. Reboot computer; press F12 (or ENTER, then F12) on boot
3. Select 1vyrain USB from boot menu
4. Computer reboots instead of booting from 1vyrain USB

I managed to work around this by changing the boot order in BIOS to have "USB HDD" above any UEFI boot option (e.g. "Windows Boot Manager" or "Pop!_OS 20.10"). The computer still reboots when selecting the 1vyrain USB from the boot menu, but it will boot to the 1vyrain USB if the user doesn't intervene in the boot process.

**Comment by digmorepaka** [comment]
Could not reproduce. 

Steps taken:

1. Load defaults
2. Disable CSM and MBR boot mode
3. Reboot
4. Select 1vyrain usb from F12 menu

Result: 1vyrain boots

**Comment by unilock** [comment]
Must be an issue on my end, then, or with the X131e in general. It doesn't look too hopeful that the X131e can be supported, anyway.
If there are no other suggestions, I suppose this issue can be closed. (paging @gch1p)

**Comment by kocoman2** [comment]
> Must be an issue on my end, then, or with the X131e in general. It doesn't look too hopeful that the X131e can be supported, anyway. If there are no other suggestions, I suppose this issue can be closed. (paging @gch1p)

I got it to work, don't know if u still have the machine, see https://github.com/n4ru/1vyrain/issues/100#issuecomment-1666646659
