### ISSUE TITLE
Possibility to hack the MRC for accepting single 16GB dimms?

### ISSUE THREAD

**Issue by chillyforest** [n4ru/1vyrain#59]
As referenced from this link:
https://www.reddit.com/r/coreboot/comments/ft4950/t440p_32gb_of_ram/
https://hardforum.com/threads/first-16gb-ddr3-udimm-so-dimm-modules.1797721/#post-1040691842

> The MRC code in the BIOS of Intel CPUs contains a command called "ASSERT" which limits the maximum value of Byte 4 to 4.If Byte 4 = 5 (for 8Gbit), the MRC will stop

Any possibility to DIY or find the author for reverse-engineering the BIOS on all the Ivy-bridged thinkpad models to update the MRC hardcode bits from BIOS file itself (if it is not splitted in separate MRC.BIN file)?

**Comment by digmorepaka** [comment]
Way outside of the scope of this project and by currently available evidence, unsupported by mobile ivy chips.

https://www.reddit.com/r/coreboot/comments/ft4950/t440p_32gb_of_ram/fn9zmj1
https://ticket.coreboot.org/issues/56
