### ISSUE TITLE
On unmodder X330 (X230+FHD mod) no video output after booting

### ISSUE THREAD

**Issue by Stan-Tastic** [n4ru/1vyrain#6]
Known issue - the Linux kernel defaults to LVDS output, which doesn't exist as eDP2 is used to connect FHD screen.

Workaround: in GRUB, add "nomodeset" to kernel parameter list.

**Comment by Stan-Tastic** [comment]
Well, duh - even though "nomodeset" was done, after booting from S3 I got blank screen.
Going blind I just pressed "1", Enter, saw flashdrive blinking, so waited... and it's flashed now, BIOS version 2.77. It worked, I guess? :-)

**Comment by n4ru** [comment]
Ah oof. I should definitely specify not to run this on an X330 without an additional patch. Thank you.

**Comment by Stan-Tastic** [comment]
So... I can't flash modded BIOS because I don't have modded BIOS? :D
And I can confirm the tool worked, I just did it "in blind". But I'd definitely love to flash the non-LVDS BIOS :D

**Comment by n4ru** [comment]
I meant that we have a prepared patch for flashing specifically for X330 devices (instead of normal X230 devices), but it wasn't published in the initial release. 📦

**Comment by Stan-Tastic** [comment]
Awesome, I'll be happy to try it out :-)

**Comment by Stan-Tastic** [comment]
Is this published now? There's no info in readme.

**Comment by n4ru** [comment]
Yes, sorry for the late response. Rev 4 onwards has option "0" for X230 detected ThinkPads, which lets you flash a modded BIOS with LVDS output disabled.

**Comment by static-void** [comment]
Hi I know this is a closed issue but I wanted to ask about compatibility with the nitrocaster FHD mod. Will it work, since nitrocaster uses LVDS brightness controls? And will it allow using a nitrocaster x230 without a custom kernel (as using coreboot does)? Thanks
