### ISSUE TITLE
T430 Reboots instead of waking up

### ISSUE THREAD

**Issue by hav0ck** [n4ru/1vyrain#60]
I'm attempting to use the 1vyrain Bio updater but when the T430 'suspends' and I press the power button to 'wake it up' the laptop reboots instead of proceeding to the next step.

There is no password set.
UEFI boot is set.
Bios was successfully downgraded using IVprep to 2.52

**Comment by digmorepaka** [comment]
Try loading UEFI defaults and using the FN key to wake it up.

**Comment by hav0ck** [comment]
I loaded defaults again and made sure UEFI/Legacy Boot was set to UEFI only and CSM Support set to Yes.
UEFI secure boot is off

Pressing the Fn key does the same thing as the power button, the computer performs a reboot.

**Comment by null31** [comment]
Did you tried with CSM Support set to No?

**Comment by hav0ck** [comment]
Just tested with CSM set to No.
Power button and Fn key both result in the computer rebooting.

I did notice that the laptop is looking for a network connection, is one required for flashing?

**Comment by null31** [comment]
Network connection is only required when you'll update with a custom bios image.

I have a little experience from flashing my T530. I did with UEFI only and CSM disabled to work flawlessly.

**Comment by n4ru** [comment]
Does this behavior occur if you attempt to wake from sleep with the power button under normal circumstances?

**Comment by hav0ck** [comment]
> Does this behavior occur if you attempt to wake from sleep with the power button under normal circumstances?

No, this behavior does not occur at any other time.

**Comment by digmorepaka** [comment]
closing because stale.
