### ISSUE TITLE
T430 can‘t boot any OS after 1vyrain

### ISSUE THREAD

**Issue by hb-de** [n4ru/1vyrain#61]
1vyrain successfully completed and rebooted to advanced version of BIOS. However, it will not boot any the installed Linux OS on /dev/sad or a Linux OS from a thumb-drive.

I was able to downgrade to Lenovo BIOS v2.64, but that also cannot boot an OS now.

I have tried in both UEFI and Legacy modes. The result is a blank screen or a reboot to BIOS.

**Comment by digmorepaka** [comment]
https://github.com/n4ru/1vyrain/issues/47

**Comment by hb-de** [comment]
It will not boot from a USB either ...

**Comment by hb-de** [comment]
Thanks, but how can I boot with SuperGrubDisk if I can’t boot from USB?

**Comment by digmorepaka** [comment]
Have you tried booting the supergrubdisk usb on a different machine to check if it's made correctly?

**Comment by hb-de** [comment]
I don’t have access to another machine.

In the end, I solved the problem by booting a live cd with syslinux (which seems to be one of the few things that can boot a machine in this state) and then using efibootmgr to create a new UEFI entry for the (otherwise) unbootable Linux OS.

Does 1vyrain always clear the UEFI boot entries?

**Comment by digmorepaka** [comment]
Yes, it reflashes the entire UEFI. All the settings stored on the SPI eeprom are gone.
