### ISSUE TITLE
T430s lost windows 7 license after this procedure

### ISSUE THREAD

**Issue by alawei** [n4ru/1vyrain#63]
Two days after this procedure, my T430s pops up a message "Windows 7 Build 7601. This copy of Windows is not genuine".  Lenovo official method could not fix the problem, and suggested BIOS modification is the cause. Lenovo uses SLIC table to store and verify windows license. Does your procedure make changes to SLIC table?

Thanks!
Alawei

**Comment by digmorepaka** [comment]
Have you tried activating windows with the key on the sticker again?

**Comment by alawei** [comment]
As I mentioned in my original post, I tried to reactivate it using lenovo official method. Then It says product key is not valid.

**Comment by digmorepaka** [comment]
Could you clarify what is "Lenovo official method" exactly? Link to a support article detailing the procedure?

**Comment by Thrilleratplay** [comment]
@alawei How do you think Lenovo's software verifies it is a on official Lenovo hardware?  It checks the BIOS, which 1vyrain replaces.  No official Lenovo BIOS, Lenovo software updates can only assume that it is no longer running on official hardware.  I would not be surprised if it checks on start up and deactivates Windows if it assumes it the hard drive has been swapped into another device.

For Windows 7, this is not a huge deal as I believe all have license key stickers but this is something to warn those who may accidentally wipe out their the Windows 8 keys.  I have a T430 that came with Windows 8 and there are no license stickers under the battery.  @n4ru  Can you add to the FAQ and prep to save the Windows key just in case it is needed to activate or reinstall Windows 8/10 (users can use their Windows 8 keys to install Windows 10)?  Personally, I use [Magical Jellybean keyfinder](https://www.magicaljellybean.com/keyfinder/) but any method will do.

**Comment by digmorepaka** [comment]
> It checks the BIOS; which 1vyrain replaces

Except all the version numbers and HW PIs stay the same, as he mentioned it's highly likely that it's the slic/slicv2 table that causes it to get deactivated

**Comment by iddq** [comment]
I have the same symptoms with the T530. Why does it only affect a few users and not everyone?

**Comment by digmorepaka** [comment]
> few users and not everyone

Because up to date versions of Windows use online activation, even though the slic table gets wiped, the hardware is still attached to a digital license.

**Comment by iddq** [comment]
oh, do you know why the entire SLIC table was deleted instead of whitelist?

**Comment by digmorepaka** [comment]
The entire flash region that contains the UEFI is erased and reflashed. The only data that survives  is data that is not stored there such as the  mac address, serial number, MTM number, and so on. SLIC table is in this flash region.

**Comment by iddq** [comment]
Is it possible to restore SLIC from backup.rom?

**Comment by BeholdersEye** [comment]
This appears to have also deactivated my Win 7 install.

Would be kindly to advise people to backup their product keys up before installing this. The "Before Installing" section seems like an ideal opportunity for doing so.

**Comment by sjholland** [comment]
> Two days after this procedure, my T430s pops up a message "Windows 7 Build 7601. This copy of Windows is not genuine". Lenovo official method could not fix the problem, and suggested BIOS modification is the cause. Lenovo uses SLIC table to store and verify windows license. Does your procedure make changes to SLIC table?
> 
> Thanks! Alawei

Hi, just thought I'd add that if you could get activated for win 7, enter the key again, and it will link it digitally to your machine like previously mentioned. You have to enter it a second time by clicking change product key,etc. I hope this could help.

**Comment by BeholdersEye** [comment]
Unfortunately my x230 was secondhand with the sticker missing so the only key was in the BIOS.

I know that technically there's a disclaimer for this sort of thing but it wouldn't hurt to mention "This will cancel your Windows activation so back those keys up, fellows!"

**Comment by sjholland** [comment]
I'm sorry and can relate thinking back a few years ago, that's how I learned the enter it twice trick. I believe there is loader software, that gets your build up and running, but not sure if that's considered bypass or don't want to post anything here that wouldn't be okay but I can remember reading about people having trouble and using winloader  that would reactivate their build, but honestly I think it might have been bypassing if I remember correctly, but might be worth checking out if no other solutions will work. I hope this could help.

**Comment by BeholdersEye** [comment]
Winloader won't work with dualboot  win/lin. Displays an "Unsupported partitiontable." Between dualboot and the BIOS now missing the SLIC table every current way of "refreshing" a windows install is not an option, per mydigitallife forums.

As a last resort I finally fixed it by buying another Windows activation code. I earnestly recommend someone edit the "Before Installing" section to warn users so as not to funnel any more money into Microsoft's bank account. Not to mention the inconvenience of having to troubleshoot a suddenly-deactivated Windows installation.
