### ISSUE TITLE
x220/Sandy Bridge - Would this work, or is there a similar software?

### ISSUE THREAD

**Issue by keeganjk** [n4ru/1vyrain#66]
This software seems to only support the -30 Thinkpads, but is it possible for this to be ported to work with Sandy Bridge devices like the x220? Is the hardware even capable of using a method like this software does to patch it? If this software cannot be used, is there anything similar that can be used to patch a custom BIOS on the x220?

**Comment by digmorepaka** [comment]
No. xx20 series does not need any bypass to allow internal flashing of a stock-based modified UEFI. McDonnelltech hosts a patched UEFI for the X220, sdx0.net hosts one for T420, and there is various other sources for the other machines.

Flashing of full binaries is currently not possible without a teardown.
