### ISSUE TITLE
USB port 12 always stays OFF in T530

### ISSUE THREAD

**Issue by cunio** [n4ru/1vyrain#67]
I don't know if this is a BIOS issue, but I cannot use Bluetooth part of AX200 card inserted to T530 WLAN PCIe port. I know that USB port 12 is wired to that PCIe. If switch on the USB port 12 in BIOS (South Bridge menu) I still do not see Intel BT device. Moreover, when I come back to BIOS USB port is off. 
If I use the same card in X230 BT build in AX200 works fine.

**Comment by pgera** [comment]
BT works with AX200 in T530 on coreboot. So it is at least partially a bios issue in that coreboot can work around it.

**Comment by digmorepaka** [comment]
closing because stale
