### ISSUE TITLE
Alternative To Discord

### ISSUE THREAD

**Issue by grravity** [n4ru/1vyrain#70]
Suggesting providing an alternative area for discussion that is more privacy friendly and decentralized/distributed.

Discord is centralized, not privacy friendly, not friendly to TOR users, sometimes forces phone number upon sign up (meaning throwaway accounts aren't easy).

Matrix may be an option.

- https://spyware.neocities.org/articles/discord.html
- https://usemumble.neocities.org/ (not suggesting mumble, but that offers a lot of information about the issues of Discord at the start.)

**Comment by digmorepaka** [comment]
We may switch platforms in the future but currently there are no plans to do so and very little incentive. The target demographic for this software generally doesn't care about privacy and other 'freedumbs' disadvantages of Discord, the few people that do care are welcome to use Github as a platform for sharing their suggestions, improvements etc.
