### ISSUE TITLE
BIOS no longer write-protected! Your machine is compatible but, unsupported. Please report the following details to GitHub Issue:

### ISSUE THREAD

**Issue by mifritscher** [n4ru/1vyrain#72]
Maschine: T430s
BIOS: G7ETB3WW
Version: 2.73
Flashsize: 16384

I used the image at https://1vyra.in/ .

**Comment by n4ru** [comment]
RTFM.

**Comment by mifritscher** [comment]
No worries, I know the downgrade path, I just didn't know what was the last vulnerable version, so I gave it a shot ;) The "official way" worked flawlessly ;)

I've some more T430s with slightly different BIOSes in the 2.6x and 2.7x range - should I try the direct way on them as well to provide you further information, or should I stick to the "downgrade to 2.59 & then use 1vyrain" path?

**Comment by n4ru** [comment]
The error is likely just due to assumptions we make in our detection, so that can probably be improved. Hold off for now since I think we know why you're getting this message, and it's likely just a false alarm.
