### ISSUE TITLE
BIOS no longer write-protected! Your machine is compatible but unsupported Machine X230T

### ISSUE THREAD

**Issue by jarugut** [n4ru/1vyrain#76]
I have the following error message over  one thinkpad X230T
Machine: X230T
BIOS:  GCET98WW
Version: 2.58
Flashsize: 122288
[dmidecode.txt](https://github.com/n4ru/1vyrain/files/6507345/dmidecode.txt)
[dmidecodesystem.txt](https://github.com/n4ru/1vyrain/files/6507346/dmidecodesystem.txt)

I attach the output of dmidecode commad with and without -t system.

Thank you for your help.

**Comment by digmorepaka** [comment]
Looks like you got another one of these oddballs where the system info tables are weird. [Follow these steps](https://github.com/n4ru/1vyrain/issues/45#issuecomment-621763634) from the dd command, your rom filename should be X230t.rom i believe.

**Comment by jarugut** [comment]
hello, do you mean execute the following after the fault automatic execution 

dd if=/dev/zero of=/tmp/pad.bin bs=1M count=8 

cat /tmp/pad.bin /root/bios/X230t.rom > /tmp/12M.rom

/root/flashrom/flashrom -p internal:laptop=force_I_want_a_brick --ifd -i bios -N -w /tmp/12M.rom 

then you can reboot.

is this correct?  about the command I understand that is creating an empty pad.bin file , then transfer to 12M the bot files pad.bin and x230t and later something flashing bios.

**Comment by digmorepaka** [comment]
Yes, that exactly. This will 
1. create an 8M binary full of 0s to 
2. pad the X230t.rom UEFI binary to the correct offset
3. flash it and only the region of the UEFI

**Comment by jarugut** [comment]
then after execute this process  I need to re-execute  the normal patch execution

is this correct? 
sorry for all the questions!  thank you a lot for your help

**Comment by digmorepaka** [comment]
Nope, after this is flashed you have the correct modified UEFI.

**Comment by jarugut** [comment]
it's works perfectly! Thank you a lot for you help!

awesome work!
