### ISSUE TITLE
Overclocking and Intel ME

### ISSUE THREAD

**Issue by h4xor666** [n4ru/1vyrain#77]
Hey there. I have a T430, and just ordered the i7-3840QM for it.

I noticed on the FAQ for 1vyrain here: https://medium.com/@n4ru/1vyrain-an-xx30-thinkpad-jailbreak-fd4bb0bdb654 that the *QM CPUs aren't able to be overclocked with the Intel ME disabled (though not officially confirmed to be the case, mind you). I couldn't find much online about why that would be, so I was wondering why that is the case?

I was hoping to externally run me_cleaner on my T430, but if I'm not able to overclock the 3840QM CPU I purchased for my T430 if I do so, I may have to reconsider. 

Best,
h4xxor666

**Comment by digmorepaka** [comment]
We do not know, nor have tested, how the stock firmware handles multiplier overclocking. In my personal opinion I don't think it needs it, because the relevant MSRs don't need ME for control, i have my 3630QM throttled with TDP which is the same MSR address as multiplier control on a me_cleaned T420. You wouldn't be able to overclock the 3840QM anyway due to the lack of thermal headroom, 3.2GHz-3.4GHz sustained is the real world limit with the triple pipe heatsink off a T420.

**Comment by h4xor666** [comment]
> We do not know, nor have tested, how the stock firmware handles multiplier overclocking. In my personal opinion I don't think it needs it, because the relevant MSRs don't need ME for control, i have my 3630QM throttled with TDP which is the same MSR address as multiplier control on a me_cleaned T420. You wouldn't be able to overclock the 3840QM anyway due to the lack of thermal headroom, 3.2GHz-3.4GHz sustained is the real world limit with the triple pipe heatsink off a T420.

According to this: https://medium.com/@n4ru/the-definitive-t430-modding-guide-3dff3f6a8e2e, it is possible to overclock it?

**Comment by digmorepaka** [comment]
This guide while mostly accurate, but is quite inaccurate in regard to what is thermally possibly. [Here](https://cdn.discordapp.com/attachments/695165783529226280/833455168090800158/T430_Temps_modded-1.png) is some thermal testing done with a 3720QM under sustained load. 3840QM tend to be slightly better binned so add around 100-200mhz to what the 37xxQM and 36xxQM chips can do in these machines. Generally it is recommended to stick to 3610QM 3630QM 3612QM 3632QM whichever is the easiest and cheapest for you to get.
