### ISSUE TITLE
x230 Tablet "compatible but not supported"

### ISSUE THREAD

**Issue by mrbigmouth502** [n4ru/1vyrain#78]
I flashed the 1vyrain iso to a USB stick, booted it in UEFI mode on my x230 Tablet, and was told to submit the following details as a GitHub issue:

Machine: X230T
BIOS: GCET98WW
Version: 2.58
Flashsize: 12288

I recall having the same issue the last time I attempted to install 1vyrain, but I cannot recall exactly how long ago that was. It wouldn't have been much more than a year ago at most. 

EDIT: I've downgraded to BIOS version 2.57. Going to see how this works out. 

EDIT2: Just tried. Pretty much the same result as last time, just different BIOS revision. Details:

Machine: X230T
BIOS: GCET97WW
Version: 2.57
Flashsize: 12288

EDIT3: Flashed it back to 2.58, after going all the way back to 1.06 and finding that that didn't even work.

**Comment by digmorepaka** [comment]
https://github.com/n4ru/1vyrain/issues/76

**Comment by slavan128** [comment]
same issue on regullar X230 - I can´t install X330 bios for 13.3" mod
(on four X230 worked without issue, but on fifth I can't install anything)

please add "force mode" with warning

**Comment by n4ru** [comment]
A little harsh on the close, but I agree. There is a force mode. It's CTRL+C and manually typing out the command. It's intentional. If you can't bother learning enough to do the force flash with a typed command, you shouldn't be trusted to do it with a menu prompt.
