### ISSUE TITLE
revert back to stock bios

### ISSUE THREAD

**Issue by ryuk171** [n4ru/1vyrain#79]
i have not backed up my old stock bios image and i have flashed a seabios coreboot image through ivyrain , now i want to revert back to stock bios, how should i do it ?

**Comment by digmorepaka** [comment]
https://medium.com/@n4ru/1vyrain-an-xx30-thinkpad-jailbreak-fd4bb0bdb654

**Comment by ryuk171** [comment]
> https://medium.com/@n4ru/1vyrain-an-xx30-thinkpad-jailbreak-fd4bb0bdb654

But even though if i get the image , i am unable to use ivyrain in coreboot , how should i flash the default bios img then

**Comment by n4ru** [comment]
flashrom

**Comment by hypadr1v3** [comment]
I tried using flashrom here but it complains about the image being 4MB while the chip is 12MB on an x230. Any easy way to fix this?

**Comment by digmorepaka** [comment]
> I tried using flashrom here but it complains about the image being 4MB while the chip is 12MB on an x230. Any easy way to fix this?

Yes you need to place the 4M of the data you want to flash into the correct region of a 12M binary.

**Comment by hypadr1v3** [comment]
Sorry I'm very new to this, how can I put it in a binary?

**Comment by digmorepaka** [comment]
https://github.com/merge/skulls/issues/137
