### ISSUE TITLE
Wishlist: add custom boot logo

### ISSUE THREAD

**Issue by Stan-Tastic** [n4ru/1vyrain#8]
This is definitely in "wish feature" category: would be super-nice to be able to specify own boot logo :-)

**Comment by n4ru** [comment]
You can flash a custom BIOS for this. I'll add a way to do this once I release the patched.

**Comment by Stan-Tastic** [comment]
Sooo... can I use your BIOS with Lenovo's WINUPTP.EXE + logo1.gif to update
the boot logo?

śr., 15 sty 2020 o 10:51 George Kushnir <notifications@github.com>
napisał(a):

**Comment by n4ru** [comment]
You'll need to `binwalk` the BIOS file, `dd` out the two or three parts outside the GIF data, and `cat` together the parts substituting in your own GIF data where the stock images were.

Keep in mind they must be EXACTLY the same size so the end result remains 4MB.

Probably not going to be included in 1vyrain, but you can flash the result from the above using the custom BIOS feature.

**Comment by Stan-Tastic** [comment]
Shame; I think better idea would be to put all 0's for 4 kB into the ROM, and the overwrite needed part with the logo image - how do you think?

Also, seeing this binwalk dump, could be useful to allow flashing custom certs - just sayin' :D
