### ISSUE TITLE
Bricked my x230 by lowering cpu power limit

### ISSUE THREAD

**Issue by RomanSedykh** [n4ru/1vyrain#80]
I tried to lower temperature of cpu by decreasing power limit for it (cannot remember exact bios option name), and at some point my laptop stopped booting at all - it just blinks once with mute/microphone buttons and with keyboard light, spins up it's fan, waits for 20-30 seconds with black screen (without screen backlight) and then cycle repeats.
I tried:
- disconnecting cmos battery - no luck.
- removing all ram sticks - laptop properly beeps as it should.
- bringing it into cervice center. guy in service center said that cpu might be dead (by lowering current for it? what?). he tried to reprogram bios chip - i have no idea which bios version he used for that, but laptop behaves just as before.

At this point i almost gave up, but maybe by some miracle there is still a solution for that (besides ordering another motherboard of course, i7 boards for x230 are quite expensive unfortunately)?

**Comment by digmorepaka** [comment]
So this is a non-volatile option therefore you have to reflash the UEFI. He might have flashed it incorrectly, the X230 is a bit weird in terms of flash layout. I suggest you obtain an SPI flasher like CH341a and flash it yourself. Also post an image of the SPI flash chip area, we can inspect it for possible physical damage. The flash chips are next to expresscard

**Comment by RomanSedykh** [comment]
Thank you for your advice. Ordered that flasher (this one to be exact https://aliexpress.ru/item/32793476447.html?spm=a2g39.orderlist.0.0.3d9d4aa6Egb5Lk , i hope this is right model).
Also, do i have do de-solder that chip, or it can be done with those wired clips?

And here is photo you requested:
![IMG_0303](https://user-images.githubusercontent.com/59629258/128216547-57b42ff9-33be-413a-b813-81b63ffe1a21.jpg)

**Comment by RomanSedykh** [comment]
Got my flasher today. So far no luck. Managed to make it read the chip, but .fl1 files from lenovo bios utility are bit too large.
First i tried to cut off last part of that file (it contains only zeroes) - laptop stopped even to blink with mute lights. Only power button lights for one second and immediately turns off. Then i tried to write bios file dump that i did before new one. Nothing. Laptop completely stopped to do anything, only power button lights up for very short amount of time when i press it.

**Comment by n4ru** [comment]
[Restoring your BIOS](https://medium.com/@n4ru/1vyrain-an-xx30-thinkpad-jailbreak-fd4bb0bdb654#5e33)

**Comment by RomanSedykh** [comment]
Thanks for that. Finally managed to reprogram chip with 2.60 (my flasher somehow not wanted to reprogram without erasing it first). Now it spins fan, but not beeps without ram sticks (before it did). And it stopped to continuously reboot. It just stays turned on. Winh fan fpinning, and power button lit up.
It shows low battery charge (it shows yellow battery sign on back when it connected), and responds to power button - i can turn it on or off at any time. That's it. Display stays without power all time.

**Comment by RomanSedykh** [comment]
[backup.zip](https://github.com/n4ru/1vyrain/files/7015629/backup.zip)
this is what i have in both chips, if it can somehow help.

**Comment by RomanSedykh** [comment]
Great news (for me at least)! I tried to program latest 2.77 bios, and laptop came back to life!
Quite interested to know why 2.60 not worked previously.
