### ISSUE TITLE
machine unsupported

### ISSUE THREAD

**Issue by T430SSS** [n4ru/1vyrain#82]
Is there a possibility to support the following machine:
T430S
BIOS: G7ETB6WW
Version: 2.76
Flashsize: 16384

or did I have to downgrade first?.
Thanks for an answer.

**Comment by digmorepaka** [comment]
That is not a compatible version. RTFM before opening an issue for no reason.

**Comment by T430SSS** [comment]
it would be nice if software wouldn't tell me to open an issue in that case, my friend.--Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 06.09.21, 14:04 schrieb Daniel ***@***.***>:

   
  That is not a compatible version. RTFM before opening an issue for no reason.

**Comment by digmorepaka** [comment]
Sorry, we will work on clarifying issue reporting better in the docs.
