### ISSUE TITLE
T530 not flashing? 

### ISSUE THREAD

**Issue by Gopherslol** [n4ru/1vyrain#84]
Thinkpad T530 with Nvidia card. Only changes from stock are RAM upgraded from 4-8GB, replacement keyboard and replacement display. Running the bios version that it shipped with it -  I want to say 1.94, but don't remember. I do know that it is below the 2.6 shown here: https://github.com/gch1p/thinkpad-bios-software-flashing-guide#bios-versions
I followed the directions exactly as far as I can tell. After going through the initial tests where the machine suspends, I was asked which bios image I wanted to flash. I selected  modified Lenovo bios. I was given two errors related to /dev/sr0 -  the CD drive (see picture) I left it running while at work and found it in the same state after returning home. After a little investigation, I discovered that a CD was in the drive. After removing and reinserting it, the same errors were repeated. have not touched it since, as I don't have a programmer on hand and do not want to make the situation worse. It is still running. No change. Any input? At this point, I would be perfectly happy getting the stock bios too. As long as it boots, I am a happy camper

**Comment by Gopherslol** [comment]
![PXL_20210917_031335737](https://user-images.githubusercontent.com/49794455/133720089-30bd66e0-fbd1-4215-9ea9-a8913188dbe6.jpg)
Nice job, self. Forgot picture in first post

**Comment by n4ru** [comment]
Have you tried upgrading to the last supported BIOS version first? Possibly related to your BIOS being too old.
