### ISSUE TITLE
Help wanted: Fan configuration on Thinkpad X230, unable to set to manual control

### ISSUE THREAD

**Issue by Agvantibo** [n4ru/1vyrain#86]
[The pwmconfig output](https://paste.gnome.org/pkoe991xy)
[List of loaded modules](https://paste.gnome.org/psno8xbvq) 
[A Neofetch for general system info](https://paste.gnome.org/p2zdubqqb)
I am using the latest default mod bios.
I understand the following phrase sounds like luser whining, but the same pwmconfig script worked fine before modding the bios and a subsequent OS reinstallation (preceded by a failed manual BTRFS snapshot removal).

**Comment by digmorepaka** [comment]
Try using thinkfan, there's also a fan control kernel option for this I believe.

**Comment by digmorepaka** [comment]
Closing as stale, comment for re-open if needed
