### ISSUE TITLE
patched-bios is old, now for t430 we have 2.82 from 2019

### ISSUE THREAD

**Issue by vitaly-zdanevich** [n4ru/1vyrain#88]
See official BIOSes here https://support.lenovo.com/by/en/downloads/ds029252

![image](https://user-images.githubusercontent.com/3514015/144495738-9272289b-3ced-4a0a-a0db-05f882e01b0d.png)

**Comment by digmorepaka** [comment]
Yeah? This is the version we run

**Comment by vitaly-zdanevich** [comment]
Oh my, time fly so fast, this is already two years from 2019... Sorry.
