### ISSUE TITLE
A few warnings/errors and no docs on them found

### ISSUE THREAD

**Issue by Veraellyunjie** [n4ru/1vyrain#90]
![SAM_7083](https://user-images.githubusercontent.com/75799052/146692691-20fe755a-f1b7-4781-9188-199387752786.JPG)
1. Network is unreachable — the LAN cable is plugged, Linux and Windows can access the internet, so network has to be reachable. I personally don't need any downloads but still…
2. PR1..PR4 warnings … is read-only — how should I treat it?
3. some flash regions are read protected — how should I treat it?
4. use a flash layout — what is this?
5. include only accessible regions — ?
6. --noverify-all switch — ?
7. see manpage — where is manpage? I searched 1vyra.in site, this github repo, medium 1vyrain FAQ and internet at large for manpage and `--noverify-all` to no avail. Where is manpage?
8. "You may see an error about flash regions being locked, this is expected and should not be a concern" — is it about the warnings that I have already got, or about those that may come ahead?

Similar warnings:
https://youtu.be/Hy-ICak5C8c?t=734

No warnings (bar network):
https://youtu.be/LSFgV_9wVow?t=432

So what is the difference between no-warnings and my set of warnings and what should I do?

_Have not checked by trying to flash — I can't afford breaking the laptop_

**Comment by digmorepaka** [comment]
![](https://i.imgur.com/ArNZ0lT.png)
