### ISSUE TITLE
Increase Turbo Ratio Max on Debian

### ISSUE THREAD

**Issue by parkournerd** [n4ru/1vyrain#91]
The documentation suggests using ThrottleStop or XTU to up the turbo ratio max, but I am running Debian instead of Windows. And I cannot get the +400MHz.

So far, I have done the following:
- disabled secure boot
- added to /etc/default/grub => GRUB_CMDLINE_LINUX_DEFAULT: msr.allow_writes=on
- sudo modprobe msr 
- sudo rdmsr --bitfield 28:28 0x0ce to ensure msr isn't locked
- sudo wrmsr -a 0x1AD 0x27272829 to set max turbo ratios for 3.9GHz, 4.0Ghz, and 4.1GHz (+400MHz)

When I run cpupower frequency-info, boost state support shows my max turbo ratios applied, but my hardware limits and current policy still show the normal max of 3.70GHz.

**Comment by biblicabeebli** [comment]
I think you have a 3740xm. I know the 3720 does not overclock, I think the same is true and you are stuck at the max single clock of 3.7 ghz.

You can, however set the all-core max turbo boost to 3.7.  I use `cpupower frequency-set xyz` and `cpupower frequency-info` to confirm.  There is also a cpupower-gui program.  (Ubuntu apt name.)

3820qm and 3840qm are over clickable some, up to 4ghz I think, xm 3920 an 3940 are unlocked.

**Comment by parkournerd** [comment]
The faq mentions my 3740qm should be able to get the 4 speed bins up: https://medium.com/@n4ru/1vyrain-an-xx30-thinkpad-jailbreak-fd4bb0bdb654.

I used cpupower and I was able to get 3.7GHz on four cores (stock is 3.7GHz on one core), but no core ever went above 3.7GHz.

To me, it seems like the changing the turbo limits was successful, but something else is preventing the clocks from exceeding stock.

**Comment by biblicabeebli** [comment]
I have found on windows - this is manufacturer platform dependant and I don't know if it applies here - that the microcode updates can reset to stock frequencies.  Given you are already overclocking a laptop, consider disabling microcode updates with kernel command line arg `dis_ucode_ldr`

This may - unclear because this repo upgrades the firmware and that may include embedding the most recent microcode - make you vulnerable to speculative execution vulnerabilities.  But, as of time of writing, there are no known attacks in the wild that use these.  I believe there was another recent academic demonstration in the last month.

**Comment by biblicabeebli** [comment]
@n4ru any chance you could comment on whether and how microcode updates are dealt with here?  Would love to know.

**Comment by digmorepaka** [comment]
There is no microcode overclocking problems on this generation.  3520M 3540M 3720QM 3740QM 3820QM 3840QM are the retail chips where you can do +4x, and 3920XM 3940XM where you can do up to 80x.

**Comment by parkournerd** [comment]
> I have found on windows - this is manufacturer platform dependant and I don't know if it applies here - that the microcode updates can reset to stock frequencies. Given you are already overclocking a laptop, consider disabling microcode updates with kernel command line arg `dis_ucode_ldr`
> 
> This may - unclear because this repo upgrades the firmware and that may include embedding the most recent microcode - make you vulnerable to speculative execution vulnerabilities. But, as of time of writing, there are no known attacks in the wild that use these. I believe there was another recent academic demonstration in the last month.

Thanks. Tried it out; easy performance boost, but it doesn't raise my max clock that +4x. I can't imagine that I am the only one on Linux, though I couldn't figure this out in 4h of research lol.

**Comment by parkournerd** [comment]
> I have found on windows - this is manufacturer platform dependant and I don't know if it applies here - that the microcode updates can reset to stock frequencies. Given you are already overclocking a laptop, consider disabling microcode updates with kernel command line arg `dis_ucode_ldr`
> 
> This may - unclear because this repo upgrades the firmware and that may include embedding the most recent microcode - make you vulnerable to speculative execution vulnerabilities. But, as of time of writing, there are no known attacks in the wild that use these. I believe there was another recent academic demonstration in the last month.

Thanks. Tried it out; easy performance boost, but it doesn't raise my max clock that +4x. I can't imagine that I am the only one on Linux, though I couldn't figure this out in 4h of research lol.

**Comment by biblicabeebli** [comment]
You are not, I'm just waiting on a cheap ebay deal for a not-3720...

fwiw I'm on a w530.

Have you tried `mitigations=off`... see github icon for appropriate emoji...

**Comment by parkournerd** [comment]
Being able to use this laptop until ARM laptops are good would be awesome :P.
You haven't tried to up your turbo with your 3720? It would be an 11% boot.

**Comment by digmorepaka** [comment]
Closing as stale, comment for re-open if needed
