### ISSUE TITLE
Thermal settings do nothing :(

### ISSUE THREAD

**Issue by vitaly-zdanevich** [n4ru/1vyrain#92]
![RDT_20220117_1733141502364849723629429](https://user-images.githubusercontent.com/3514015/149788665-89a2822d-107a-46e8-9be5-8928192c5766.jpg)

I increased ’Active Trip Point’ but still hear the fan at 50 degree :(

**Comment by digmorepaka** [comment]
As is written in the FAQ some options don't work and or aren't available with every operating system. There is nothing that we can do about this.
