### ISSUE TITLE
Update documentation for the thinkpad-ec keyboard mod

### ISSUE THREAD

**Issue by kris545545** [n4ru/1vyrain#93]
Hello!
I had trouble flashing the thinkpad-ec keyboard mod after 1vyrain as the BIOS wouldn't "see" the new EC firmware waiting to get flashed, so I ran IVprep from Windows again to flash BIOS version 2.60 and trigger a full flash, which flashed the patched EC correctly. After that, I flashed 1vyrain with the installer successfully, again.

**Comment by digmorepaka** [comment]
The latest UEFI version does not flash modified ECs, this is known and already mentioned in the documentation. https://github.com/n4ru/1vyrain#installing
