### ISSUE TITLE
Cannot enable virtualization on Thinkpad T530

### ISSUE THREAD

**Issue by ThinkpadT530user** [n4ru/1vyrain#95]
I've got a problem where when I enable virtualization and save changes and reboot, virtualization automatically disables. It is not a windows problem because I rebooted directly back into the bios after saving changes and virtualization was disabled.

**Comment by digmorepaka** [comment]
Which menu are you making this change in? Advanced menu or security menu?

**Comment by ThinkpadT530user** [comment]
advanced menu

**Comment by digmorepaka** [comment]
Do it through the security menu(or regular config, don't quite remember which one it is)

**Comment by ThinkpadT530user** [comment]
just enabled it from the security menu and it is fine now. Thanks!
