### ISSUE TITLE
t430: feedback after 1vyrain

### ISSUE THREAD

**Issue by tryfail** [n4ru/1vyrain#96]
Hi, just want to leave some feedback, because I had a few mishaps.

**To sum up, I ran IVprep and then 1vyrain and was able to use an intel 7260 AC wireless chip that I could not use before on my T430 due to the chip whitelist. I am wondering if there are any known issues regarding the buttons above touchpad, which broke after upgrade. More details below**

The flashing process itself went fine. However, a few (~3) reboots after within a couple of minutes of flashing, the trackpoint buttons stopped working (only the 3 buttons just above the touchpad). Maybe one or two reboots after, since I suspected this was a Windows issue, a memory stick failed. This all happened before disassembly of keyboard in order to replace the wireless chip.

Since I had an extra keyboard for parts of same FRU (and also parts NO.), I replaced it in and the 3 buttons above touchpad worked just fine. Then came the arduous task of filling up the donor keyboard. Some buttons are not quite right because of damaged rubber caps, so will probably need to buy another keyboard this year, if there is no fix.

Booting with the bad memory stick (4GB lenovo part) resulted in infinite black screen on boot.

Glad I saved this for sunday evening.

**Comment by digmorepaka** [comment]
Keyboard  sounds like an unfortunate hardware failure. The ram, is this a 1066MT/s stick perhaps from an older model? Newer UEFI versions are incapable of training 800MT/s and 1066MT/s memory.

**Comment by tryfail** [comment]
The RAM stick isa 

> Keyboard sounds like an unfortunate hardware failure. The ram, is this a 1066MT/s stick perhaps from an older model? Newer UEFI versions are incapable of training 800MT/s and 1066MT/s memory.

The RAM stick is a [4GB PC3-12800 DDR3-1600MHz SODIMM (FRU: 03X6561)] . Not sure if old, but at least it is aged, I'll buy another one. It did work on another device but it seems iffy and will probably fail if it reaches bad thermals.
